# Generated by Django 5.2.4 on 2025-07-21 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubPRLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_number", models.IntegerField()),
                ("title", models.CharField(max_length=512, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("pr_url", models.URLField(max_length=1024)),
                ("username", models.CharField(max_length=255)),
                ("action", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "webhook_log",
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_gateway_name", models.CharField(max_length=255)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Failed"), ("1", "Success"), ("2", "Pending")],
                        default="2",
                        max_length=1,
                    ),
                ),
                ("response_data", models.TextField(blank=True, null=True)),
                ("request_data", models.TextField(blank=True, null=True)),
                ("created_by", models.BigIntegerField(default=0)),
                ("updated_by", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPaymentGateway",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_gateway_id", models.BigIntegerField()),
                ("payment_gateway_name", models.CharField(max_length=255)),
                ("credentials", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Inactive"), ("1", "Active")],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "is_live_mode",
                    models.CharField(
                        choices=[("0", "Inactive"), ("1", "Active")],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "has_apple_pay",
                    models.CharField(
                        choices=[("0", "Inactive"), ("1", "Active")],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "has_google_pay",
                    models.CharField(
                        choices=[("0", "Inactive"), ("1", "Active")],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "has_card_pay",
                    models.CharField(
                        choices=[("0", "Inactive"), ("1", "Active")],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0)),
                ("updated_by", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_gateways",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_payment_gateway",
            },
        ),
    ]
