# Generated by Django 5.2.4 on 2025-07-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlog",
            name="response_data",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
