# Generated by Django 5.2.4 on 2025-07-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_alter_paymentlog_response_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentlog",
            old_name="response_data",
            new_name="responses_data",
        ),
    ]
