# Generated by Django 5.2.4 on 2025-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0003_rename_response_data_paymentlog_responses_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentlog",
            name="responses_data",
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="response_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
