# Generated by Django 5.2.4 on 2025-07-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0004_remove_paymentlog_responses_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentlog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="paymentlog",
            name="updated_by",
        ),
    ]
