# Generated by Django 5.2.4 on 2025-07-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0005_remove_paymentlog_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentlog",
            name="user",
        ),
    ]
