# Generated by Django 5.2.4 on 2025-07-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0006_remove_paymentlog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubprlog",
            name="delivery_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
